# Generated by Django 4.1 on 2022-08-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_stations', models.CharField(max_length=200, verbose_name='Estação de Trabalho')),
                ('employee_name', models.CharField(max_length=150, verbose_name='Funcionário')),
                ('shift', models.CharField(max_length=20, verbose_name='Turno')),
                ('appointment_date', models.DateTimeField(verbose_name='Agendamento')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Workstations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_stations', models.CharField(max_length=200, verbose_name='Estação de Trabalho')),
            ],
            options={
                'verbose_name': 'Estação de Trabalho',
                'verbose_name_plural': 'Estações de Trabalho',
                'ordering': ['work_stations'],
            },
        ),
    ]
