# Generated by Django 4.1 on 2022-08-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='appointment_date',
            field=models.DateTimeField(default='%d/%m/%Y %H:%M:%S', verbose_name='Agendamento'),
        ),
    ]
